package view;
import controller.ClienteControle;
import java.util.Random;
import model.Conta;
import controller.InvestimentoControle;
import javax.swing.JOptionPane;
public class ViewInvestir extends javax.swing.JFrame {
    int login;
    String senha;
    public void pegarDados(int login, String senha){
        this.login = login;
        this.senha = senha;
    }
    public ViewInvestir() {
        initComponents();
        Random gerador = new Random(2);
        jEspecial.setText(Float.toString((float) (gerador.nextFloat(3)+ 0.5)));
        jPoupanca.setText(Float.toString(gerador.nextFloat((float) 1.5)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        lQuantia = new javax.swing.JLabel();
        jValor = new javax.swing.JTextField();
        btPoupanca = new javax.swing.JButton();
        btEspecial = new javax.swing.JButton();
        lPoupanca = new javax.swing.JLabel();
        jPoupanca = new javax.swing.JTextField();
        lEspecial = new javax.swing.JLabel();
        jEspecial = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTitulo.setText("Investir");

        lQuantia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lQuantia.setText("Quantia que deseja investir");

        jValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jValorActionPerformed(evt);
            }
        });

        btPoupanca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btPoupanca.setText("Poupança");
        btPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPoupancaActionPerformed(evt);
            }
        });

        btEspecial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btEspecial.setText("Especial");
        btEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEspecialActionPerformed(evt);
            }
        });

        lPoupanca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lPoupanca.setText("Rendimento Poupança / mes");

        jPoupanca.setEditable(false);

        lEspecial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lEspecial.setText("Rendimento Especial / ano");

        jEspecial.setEditable(false);

        btVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVoltar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btPoupanca)
                                .addGap(18, 18, 18)
                                .addComponent(btEspecial))
                            .addComponent(jValor)
                            .addComponent(lQuantia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jEspecial)
                            .addComponent(jPoupanca)
                            .addComponent(lPoupanca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEspecial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQuantia)
                    .addComponent(lPoupanca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEspecial)
                    .addComponent(btPoupanca))
                .addGap(37, 37, 37)
                .addComponent(btVoltar)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        ViewUsuario tela = new ViewUsuario();
        tela.receberDados(login, senha);
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPoupancaActionPerformed
        try{
            int opcao = 1;
            InvestimentoControle investir = new InvestimentoControle();
            Conta conta = new Conta();
            ClienteControle pegar = new ClienteControle();
            conta = pegar.consultar3(login, senha);
            float valor = Float.valueOf(jValor.getText());
            if(conta.getSaldo() >= valor){
                investir.investir(login, senha, opcao, Float.valueOf(jValor.getText()), conta, Float.valueOf(jPoupanca.getText()));
                JOptionPane.showMessageDialog(null, "Investimento Realizado com sucesso", "Investimento feito", 1);
            }else {
                JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Transferencia Fracassada", 1);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Insira Dados Validos", "Falha no Login", 2);
        }
    }//GEN-LAST:event_btPoupancaActionPerformed

    private void btEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEspecialActionPerformed
        int opcao = 2;
        InvestimentoControle investir = new InvestimentoControle();
        Conta conta = new Conta();
        ClienteControle pegar = new ClienteControle();
        conta = pegar.consultar3(login, senha);
        investir.investir(login, senha, opcao, Float.valueOf(jValor.getText()), conta, Float.valueOf(jEspecial.getText()));
        JOptionPane.showMessageDialog(null, "Investimento Realizado com sucesso", "Investimento feito", 1);
    }//GEN-LAST:event_btEspecialActionPerformed

    private void jValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jValorActionPerformed

    }//GEN-LAST:event_jValorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEspecial;
    private javax.swing.JButton btPoupanca;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField jEspecial;
    private javax.swing.JTextField jPoupanca;
    private javax.swing.JTextField jValor;
    private javax.swing.JLabel lEspecial;
    private javax.swing.JLabel lPoupanca;
    private javax.swing.JLabel lQuantia;
    private javax.swing.JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
