package view;
import model.Conta;
import controller.ContaControle;
import javax.swing.JOptionPane;
import static java.lang.Integer.*;
    
public class ViewTransferir extends javax.swing.JFrame {

    public ViewTransferir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lValor = new javax.swing.JLabel();
        jQuantia = new javax.swing.JTextField();
        lDest = new javax.swing.JLabel();
        jDest = new javax.swing.JTextField();
        lTitulo = new javax.swing.JLabel();
        btTransf = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lValor.setText("Valor");

        lDest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lDest.setText("Conta do Destinatario");

        lTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTitulo.setText("Transferir quantia");

        btTransf.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btTransf.setText("Transferir");
        btTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransfActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btTransf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btVoltar))
                        .addComponent(lDest, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lValor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jQuantia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jDest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lDest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTransf)
                    .addComponent(btVoltar))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransfActionPerformed
        ContaControle ctrl = new ContaControle();
        ctrl.transferir(Integer.parseInt(jDest.getText()), Integer.parseInt(jQuantia.getText()));
        JOptionPane.showMessageDialog(null, "Transferencia realizada com sucesso", "Transferencia realizada", 1);
    }//GEN-LAST:event_btTransfActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        ViewUsuario tela = new ViewUsuario();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTransf;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField jDest;
    private javax.swing.JTextField jQuantia;
    private javax.swing.JLabel lDest;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JLabel lValor;
    // End of variables declaration//GEN-END:variables
}
