/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author leoch
 */
public class ViewInvestir extends javax.swing.JFrame {

    /**
     * Creates new form ViewInvestir
     */
    public ViewInvestir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        lQuantia = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btPoupanca = new javax.swing.JButton();
        btEspecial = new javax.swing.JButton();
        lPoupanca = new javax.swing.JLabel();
        jPoupanca = new javax.swing.JTextField();
        lEspecial = new javax.swing.JLabel();
        jEspecial = new javax.swing.JTextField();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lTitulo.setText("Investir");

        lQuantia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lQuantia.setText("Quantia que deseja investir");

        btPoupanca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btPoupanca.setText("Poupança");

        btEspecial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btEspecial.setText("Especial");

        lPoupanca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lPoupanca.setText("Rendimento Poupança / mes");

        jPoupanca.setEditable(false);

        lEspecial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lEspecial.setText("Rendimento Especial / ano");

        jEspecial.setEditable(false);

        btVoltar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVoltar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btPoupanca)
                                .addGap(18, 18, 18)
                                .addComponent(btEspecial))
                            .addComponent(jTextField1)
                            .addComponent(lQuantia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jEspecial)
                            .addComponent(jPoupanca)
                            .addComponent(lPoupanca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lEspecial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lQuantia)
                    .addComponent(lPoupanca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lEspecial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEspecial)
                    .addComponent(btPoupanca))
                .addGap(37, 37, 37)
                .addComponent(btVoltar)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        ViewUsuario tela = new ViewUsuario();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEspecial;
    private javax.swing.JButton btPoupanca;
    private javax.swing.JButton btVoltar;
    private javax.swing.JTextField jEspecial;
    private javax.swing.JTextField jPoupanca;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lEspecial;
    private javax.swing.JLabel lPoupanca;
    private javax.swing.JLabel lQuantia;
    private javax.swing.JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
